export const ACTIONS = {
	FETCH_POSTS: 'FETCH_POSTS',
	FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
	FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',
	
	FETCH_SINGLE_POST: 'FETCH_SINGLE_POST',
	FETCH_SINGLE_POST_SUCCESS: 'FETCH_SINGLE_POST_SUCCESS',
	FETCH_SINGLE_POST_ERROR: 'FETCH_SINGLE_POST_ERROR',
	RESET_POSTS: 'RESET_POSTS',
};