export const ACTIONS = {
	FETCH_BLOG_POSTS: 'FETCH_USER_BLOG_POSTS',
	FETCH_BLOG_POSTS_SUCCESS: 'FETCH_USER_BLOG_POSTS_SUCCESS',
	FETCH_BLOG_POSTS_ERROR: 'FETCH_USER_BLOG_POSTS_ERROR',
	RESET_USER: 'RESET_USER',
	EDIT_RECORD: 'EDIT_RECORD',
	EDIT_RECORD_SUBMIT: 'EDIT_RECORD_SUBMIT',
	EDIT_RECORD_SUBMIT_SUCCESS: 'EDIT_RECORD_SUBMIT_SUCCESS',
	EDIT_RECORD_SUBMIT_ERROR: 'EDIT_RECORD_SUBMIT_ERROR',
	CLOSE_EDIT_RECORD: 'CLOSE_EDIT_RECORD',
	DELETE_RECORD: 'DELETE_RECORD',
	DELETE_RECORD_SUCCESS: 'DELETE_RECORD_SUCCESS',
	DELETE_RECORD_ERROR: 'DELETE_RECORD_ERROR',
};

export const RECORD_TYPES = {
	BLOG: 'BLOG',
	POST: 'POST',
};